# Generated by Django 6.0.6 on 2026-06-29 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, max_length=200)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('featured', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Endereço')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('postal_code', models.CharField(blank=True, max_length=12, verbose_name='CEP')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sport', models.CharField(choices=[('futsal', 'Futsal'), ('tenis', 'Tênis'), ('volei', 'Vôlei'), ('beach_tennis', 'Beach Tennis'), ('basquete', 'Basquete')], max_length=20)),
                ('size', models.CharField(blank=True, max_length=60, verbose_name='Tamanho/dimensões')),
                ('surface', models.CharField(blank=True, max_length=60, verbose_name='Piso')),
                ('is_indoor', models.BooleanField(default=False, verbose_name='Coberta')),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('slot_minutes', models.PositiveIntegerField(default=60)),
                ('available_for_rent', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('contact', models.CharField(blank=True, max_length=40)),
                ('image', models.CharField(blank=True, max_length=200)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='booking.club')),
            ],
            options={
                'ordering': ['club_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CourtBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(default='Indisponível temporariamente', max_length=200)),
                ('until', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('court', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='block', to='booking.court')),
            ],
        ),
        migrations.CreateModel(
            name='CourtSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')])),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='booking.court')),
            ],
            options={
                'ordering': ['court_id', 'weekday', 'opening_time'],
                'constraints': [models.UniqueConstraint(fields=('court', 'weekday', 'opening_time'), name='uniq_schedule_window')],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('status', models.CharField(choices=[('confirmed', 'Confirmada'), ('cancelled', 'Cancelada')], default='confirmed', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='booking.court')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('court', 'date', 'start_time'), name='uniq_reservation_slot')],
            },
        ),
        migrations.CreateModel(
            name='SlotBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_blocks', to='booking.court')),
            ],
            options={
                'ordering': ['court_id', 'date', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('court', 'date', 'start_time'), name='uniq_slot_block')],
            },
        ),
    ]
